[licenses]
allow = [
  "MIT",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "Zlib",
  "BSD-3-Clause",
  "Unlicense",
  "Unicode-3.0",
]
confidence-threshold = 0.95
private = {ignore = true}

[advisories]
unmaintained = "all"

[bans]
multiple-versions = "allow"
